---
name: 🆕 Renovate
"on":
  workflow_dispatch:
  schedule:
    - cron: "3 17 * * 1"
  push:
    branches:
      - main
    paths:
      - .github/workflows/renovate.yaml
      - renovate.json5

jobs:

  renovate:
    uses: kdeldycke/repomatic/.github/workflows/renovate.yaml@ba0f8e2bc9d7967d598f7f4f1f10ff923edcc1a7 # v6.18.4
    secrets:
      REPOMATIC_PAT: ${{ secrets.REPOMATIC_PAT }}
